apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sg
  namespace: skix-gateway
spec:
  gatewayClassName: sg
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
        - name: sg-tls-sec
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
  #addresses:
  #  - type: IPAddress
  #    value: "20.249.26.207" # 여기에 미리 예약한 공용 IP를 입력합니다.
