apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: sg-config
  namespace: skix-gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: "skix-gateway-svc" # 여기서 서비스 이름을 정의합니다!
        type: LoadBalancer
        annotations:
          # Azure 고정 IP의 이름을 지정 (이게 없으면 새 IP가 생성됨)
          service.beta.kubernetes.io/azure-pip-name: "${GATEWAY_PIP}"
          # 만약 IP가 노드 리소스 그룹이 아닌 다른 곳에 있다면 아래 추가
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "MC_rg-s1tops-poc_aks-test_koreacentral"  # 다른 리소스 그룹이면 명칭 지정
          service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
      envoyDeployment:
        #replicas: 1   #POD수 정의 HorizontalPodAutoscaler 와 충돌이 발생하므로 주석 처리함
        pod:
          labels:
            app: skix-gateway-proxy
          # [중요] spec 키워드는 여기서 한 번만 사용하며, nodeSelector를 포함합니다.
          nodeSelector:
            agentpool: servicepool # 실제 AKS Service Pool 이름
